CREATE TABLE IF NOT EXISTS `USUARIO` (
  `CODIGO` varchar(30) NOT NULL,
  `NOME` varchar(60) DEFAULT NULL,
  `DT_NASCIMENTO` datetime(3) DEFAULT NULL,
  `FOTO` varchar(10000) DEFAULT NULL,
  PRIMARY KEY (`CODIGO`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;